[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
haku.path = "crates/haku"
log = "0.4.22"

[profile.wasm-dev]
inherits = "dev"
panic = "abort"

[profile.wasm-release]
inherits = "release"
panic = "abort"
